{
  pkgs,
  lib,
  config,
  ...
}: {
  sops.secrets = {
    gitea_mirror_env = {
      sopsFile = ./secrets.yaml;
    };
  };

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}" = {
      allowedUDPPorts = [53 4321];
      allowedTCPPorts = [53 4321];
    };
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."gitea-mirror" = {
    image = "ghcr.io/raylabshq/gitea-mirror:latest";
    environmentFiles = [config.sops.secrets.gitea_mirror_env.path];
    volumes = [
      "/persist/docker-volumes/gitea-mirror/data:/app/data:rw"
    ];
    ports = [
      "4321:4321"
    ];
    user = "1000:100";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"wget\", \"--no-verbose\", \"--tries=3\", \"--spider\", \"http://localhost:4321/api/health\"]"
      "--health-interval=30s"
      "--health-retries=5"
      "--health-start-period=15s"
      "--health-timeout=10s"
      "--network-alias=gitea-mirror"
      "--network=gitea_mirror_default"
    ];
  };

  systemd.services."podman-gitea-mirror" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-gitea_mirror_default.service"
    ];
    requires = [
      "podman-network-gitea_mirror_default.service"
    ];
    partOf = [
      "podman-compose-gitea-mirror-root.target"
    ];
    wantedBy = [
      "podman-compose-gitea-mirror-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-gitea_mirror_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f gitea_mirror_default";
    };
    script = ''
      podman network inspect gitea_mirror_default || podman network create gitea_mirror_default
    '';
    partOf = ["podman-compose-gitea-mirror-root.target"];
    wantedBy = ["podman-compose-gitea-mirror-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-gitea-mirror-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
